name: flutter_overpass
description: Flutter plugin to use overpass api with flutter. Support both Android and iOS.
version: 1.1.0
homepage: https://github.com/nusanet/flutter_overpass.git

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  equatable: ^2.0.5
  json_annotation: ^4.5.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  json_serializable: ^6.0.1
  mockito: ^5.3.2

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: id.net.nusa.plugin.FlutterOverpassPlugin.flutter_overpass
        pluginClass: FlutterOverpassPlugin
      ios:
        pluginClass: FlutterOverpassPlugin
